version: "2.1"
services:
  jobmanager:
    image: flink
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    depends_on:
       - hadoop
    links:
       - "hadoop"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
 
  taskmanager:
    image: flink
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
      - hadoop
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  hadoop:
   image: fredzhao04/docker-hadoop3.1.2_v6.0
   command: ["/root/start-container.sh"]
   ports:
     - "50070:50070"
     - "8088:8088"
     - "9000:9000"
     - "8020:8020"
   expose:
     - "8020"
     - "8042"
     - "8088"
     - "9000"
     - "10020"
     - "19888"
     - "50010"
     - "50020"
     - "50070"
     - "50075"
     - "50090"
